services:
  swg_api:
    build:
      context: .
      dockerfile: swg_api/Dockerfile
    container_name: swg_api_demo2
    env_file:
      - ./config/.env
    ports:
      - "3001:3001"

  swg:
    build:
      context: .
      dockerfile: swg/Dockerfile
    container_name: swg_demo2
    depends_on:
      - swg_api
    ports:
      - "3000:3000"

