services:
  swg_api:
    build:
      context: .
      dockerfile: swg_api/Dockerfile
    container_name: swg_api_demo2
    env_file:
      - ./config/.env
    ports:
      - "3003:3003"

  swg:
    build:
      context: .
      dockerfile: swg/Dockerfile
    container_name: swg_demo2
    depends_on:
      - swg_api
    ports:
      - "3002:3002"

